version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=api_wallet
      - POSTGRES_USER=api_wallet
      - POSTGRES_PASSWORD=api_wallet
      - OPEN_EXCHANGE_RATE_API_ID=460c5586fcad4fa7ac527007d31eebba
    ports:
      - "8001:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    restart: always
    image: redis:6.2.6
    volumes:
      - redis:/.data:rw
    ports:
      - "6380:6379"

volumes:
  database:
  redis:
