# Generated by Django 3.2.9 on 2021-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
    ]
