# Generated by Django 3.2.9 on 2021-11-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_test_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='test_field2',
        ),
    ]
