# Generated by Django 3.2.9 on 2021-11-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_currency'),
        ('transactions', '0004_auto_20211111_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallet'),
        ),
    ]
