# Generated by Django 3.2.9 on 2021-11-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='contact',
        ),
    ]
